"""Generates src/styles/icons.css from the inline sprite in src/components/IconSprite.astro.

Each icon becomes a CSS class (same name as the sprite id, e.g. .l-sandwich) that sets --ic to a data-URI SVG.
Elements with class "ico" (zero specificity, so size classes win) paint that shape as a mask in the current text colour: one element per icon instead of a
<use> shadow tree, which keeps style and layout work small on pages with hundreds of icons.

Run: python3 scripts/build-icons.py
"""
import re
import urllib.parse
from pathlib import Path

root = Path(__file__).resolve().parent.parent
sprite = (root / "src/components/IconSprite.astro").read_text()
out = [
    "/* Generated by scripts/build-icons.py from IconSprite.astro – do not edit by hand. */",
    ":where(.ico){display:inline-block;flex:none;width:1em;height:1em;vertical-align:middle;background-color:currentColor;"
    "-webkit-mask:var(--ic) center/contain no-repeat content-box;mask:var(--ic) center/contain no-repeat content-box}",
]
count = 0
# Prettier nests the symbols in the sprite, so each symbol's own shape runs from its opening tag to the next
# <symbol or </symbol.
for m in re.finditer(r'<symbol\b([^>]*)>', sprite):
    attrs = m.group(1)
    name = re.search(r'\bid="([^"]+)"', attrs).group(1)
    view = re.search(r'viewBox="([^"]+)"', attrs).group(1)
    end = min(i for i in (sprite.find("<symbol", m.end()), sprite.find("</symbol", m.end())) if i >= 0)
    body = re.sub(r"\s+", " ", sprite[m.end():end]).replace("currentColor", "#000")
    body = re.sub(r"> <", "><", body).replace("</svg >", "</svg>")
    svg = (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{view}" fill="none" stroke="#000" stroke-width="2" '
        f'stroke-linecap="round" stroke-linejoin="round">{body.strip()}</svg>'
    )
    uri = "data:image/svg+xml," + urllib.parse.quote(svg, safe=" =:/,;'")
    out.append(f'.{name}{{--ic:url("{uri}")}}')
    count += 1
(root / "src/styles/icons.css").write_text("\n".join(out) + "\n")
print(f"{count} icons written to src/styles/icons.css")
